services:

  traefik:
    image: traefik:v3.2

  php:
    depends_on:
      - traefik
  
  node:
    image: node:20
    container_name: camt-portal-node
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"
  